[project]
name = "amlas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numba>=0.63.1",
    "numpy<=2.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
]
